username: johnunknowneditor@outlook.com
password: Ineed2work
phone_number: 6132615972

positions:
- Database
- Developer
- # Another position you want to search for
- # A third position you want to search for

locations:
 Toronto
 # A second location you want to search in 

# --------- Optional Parameters -------
uploads:
 Resume: C:\Users\Junhong Chen\Desktop\Resume.docx
 Cover Letter: C:\Users\Junhong Chen\Desktop\CoverLetter(mod).docx
#  Photo: # PATH TO photo


output_filename:
 C:\Users\Junhong Chen\Desktop\output.csv

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
